### ISSUE TITLE
Error on strong text

### ISSUE THREAD

**Issue by robfentress** [ucfcdl/UDOIT#61]
UDOIT indicates that the following HTML is inaccessible:
`<p><strong>Bold text</strong></p>`

While I could certainly understand a warning in this instance, there are instances where you may want to indicate that a line of text is important, but not a heading.

**Comment by bagofarms** [comment]
UDOIT does not indicate that it is inaccessible.  It is a suggestion, rather than an error.  Also, the latest version of UDOIT changes the wording of this error to "Avoid using styles for document structure."  That should make it easier to understand what UDOIT is suggesting, and for the user to ignore it if it doesn't apply to their situation.
